-- Switch to ACCOUNTADMIN role
USE ROLE ACCOUNTADMIN;

-- Create warehouse for YouTube analytics
CREATE WAREHOUSE IF NOT EXISTS YOUTUBE_ANALYTICS_WH
    WITH WAREHOUSE_SIZE = 'X-SMALL'
    AUTO_SUSPEND = 60
    AUTO_RESUME = TRUE
    INITIALLY_SUSPENDED = TRUE;

-- Create database for YouTube data
CREATE DATABASE IF NOT EXISTS YOUTUBE_ANALYTICS_DB;

-- Create role for dbt operations
CREATE ROLE IF NOT EXISTS YOUTUBE_ANALYTICS_ROLE;

-- Check permissions on warehouse
SHOW GRANTS ON WAREHOUSE YOUTUBE_ANALYTICS_WH;

-- Grant warehouse usage permissions
GRANT USAGE ON WAREHOUSE YOUTUBE_ANALYTICS_WH
    TO ROLE YOUTUBE_ANALYTICS_ROLE;

-- Grant role to user (replace with your username)
GRANT ROLE YOUTUBE_ANALYTICS_ROLE
    TO USER your_snowflake_username;

-- Grant all permissions on database
GRANT ALL ON DATABASE YOUTUBE_ANALYTICS_DB
    TO ROLE YOUTUBE_ANALYTICS_ROLE;

-- Switch to analytics role
USE ROLE YOUTUBE_ANALYTICS_ROLE;

-- Create schemas for different environments
CREATE SCHEMA IF NOT EXISTS YOUTUBE_ANALYTICS_DB.RAW_DATA;
CREATE SCHEMA IF NOT EXISTS YOUTUBE_ANALYTICS_DB.ANALYTICS_DEV;
CREATE SCHEMA IF NOT EXISTS YOUTUBE_ANALYTICS_DB.ANALYTICS_PROD;
