{% macro create_schemas() %}
  {% set sql %}
    USE ROLE ACCOUNTADMIN;
    USE DATABASE YOUTUBE_ANALYTICS_DB;
    CREATE SCHEMA IF NOT EXISTS ANALYTICS_DEV;
    CREATE SCHEMA IF NOT EXISTS ANALYTICS_PROD;
    GRANT ALL ON SCHEMA ANALYTICS_DEV TO ROLE ACCOUNTADMIN;
    GRANT ALL ON SCHEMA ANALYTICS_PROD TO ROLE ACCOUNTADMIN;
    GRANT ALL ON FUTURE TABLES IN SCHEMA ANALYTICS_DEV TO ROLE ACCOUNTADMIN;
    GRANT ALL ON FUTURE VIEWS IN SCHEMA ANALYTICS_DEV TO ROLE ACCOUNTADMIN;
  {% endset %}
  
  {% do run_query(sql) %}
{% endmacro %}